apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yaqnb5k1i-nodejs 
  janus-idp.io/tekton: yaqnb5k1i-nodejs
  backstage.io/kubernetes-id: yaqnb5k1i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yaqnb5k1i-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml