apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yaqnb5k1i-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yaqnb5k1i-nodejs 
  name: yaqnb5k1i-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yaqnb5k1i-nodejs 
